### ISSUE TITLE
Would like to ask if the microphone is working

### ISSUE THREAD

**Issue by lulujyc** [AniKulkarn/Hackintosh-ThinkPad-E14#24]
Good day,

I'm considering to buy a ThinkPad E14 for hackintosh for its trackpoint and M.2 wireless. However, as many modern laptops utilize the Intel Smart Sound technology for the microphone, which is not compatible with macOS, I would like to confirm the working status of the microphone for this laptop prior to buying. Thank you very much!

**Comment by AniKulkarn** [comment]
Hi! Everything is working except HDMI (which too, is working for one of our contributors - but we're not able to get it working on our laptops). But yes, microphone, sound, everything is working perfectly fine.

**Comment by lulujyc** [comment]
> Hi! Everything is working except HDMI (which too, is working for one of our contributors - but we're not able to get it working on our laptops). But yes, microphone, sound, everything is working perfectly fine.

Thank you! Good to know that Lenovo didn't choose to integrate Intel SST to all their laptops. However it was a pity that they chose to do such for the X1 series lineup. Many thanks!
