### ISSUE TITLE
How to use fan control

### ISSUE THREAD

**Issue by 799953468** [AniKulkarn/Hackintosh-ThinkPad-E14#25]
How to use fan control(yogasmc), ec can't rw

**Comment by AniKulkarn** [comment]
You want to control the fan manually? I don't think that's a thing in macOS :D

**Comment by 799953468** [comment]
> You want to control the fan manually? I don't think that's a thing in macOS :D

The fan is very slow when the computer is first turned on，Return to normal during sleep

**Comment by AniKulkarn** [comment]
> > You want to control the fan manually? I don't think that's a thing in macOS :D
> 
> The fan is very slow when the computer is first turned on，Return to normal during sleep

Oh. But is the computer overheating? What power profile did you choose while configuring cpufriend.kext?

**Comment by 799953468** [comment]
> > > You want to control the fan manually? I don't think that's a thing in macOS :D
> > 
> > 
> > The fan is very slow when the computer is first turned on，Return to normal during sleep
> 
> Oh. But is the computer overheating? What power profile did you choose while configuring cpufriend.kext?

performance。   Above 80 ℃

**Comment by AniKulkarn** [comment]
I chose balanced and it works fine for me. 80 degrees is freaking hot man, you should reset your CPUFriend profile immediately!

**Comment by 799953468** [comment]
> I chose balanced and it works fine for me. 80 degrees is freaking hot man, you should reset your CPUFriend profile immediately!

ok.  thx
