### ISSUE TITLE
fan controller

### ISSUE THREAD

**Issue by xiaogumu** [AniKulkarn/Hackintosh-ThinkPad-E14#33]
Hello, is your fan normal? My fan can be identified. The ISTAT menus shows that the speed is 0 and the temperature is generally controlled at 50 degrees, but the fan speed is relatively large and the frequency is high

**Comment by whoisguiguesse** [comment]
Mine is also like this. The battery ends up not lasting anything because the process is always at high frequency and the cooler accelerated.

**Comment by Zer0xPoint** [comment]
same

**Comment by AniKulkarn** [comment]
Strange. This is all related to how you configure your CPUFriend.kext. I have set mine on medium high performance setting.

**Comment by xiaogumu** [comment]
> Strange. This is all related to how you configure your CPUFriend.kext. I have set mine on medium high performance setting.

Can you explain in detail how you configure it? I really want to know.
