### ISSUE TITLE
monterey update

### ISSUE THREAD

**Issue by Zer0xPoint** [AniKulkarn/Hackintosh-ThinkPad-E14#34]
opencore v0.6.3 not working in Monterey

**Comment by AniKulkarn** [comment]
Yes. I will be updating the OC soon.

**Comment by Zer0xPoint** [comment]
good to know, thx for ur work

**Comment by whoisguiguesse** [comment]
I updated opencore to the latest version and yet this EFI displays kernel panic. But what really deserves attention is the energy efficiency, the battery lasts very little, even the notebook with all apps closed.
