### ISSUE TITLE
Internal Microphone cannot be selected after plugging in wired headphone-microphone. 

### ISSUE THREAD

**Issue by pratikmullick** [AniKulkarn/Hackintosh-ThinkPad-E14#35]
The internal microphone is permanently disabled after connecting a wired headphone-microphone. Anyone else with the same issue?

**Comment by AniKulkarn** [comment]
Not really having this problem at my end :(

**Comment by pratikmullick** [comment]
Sorted out the issue. Had to reset NVRAM from OpenCore boot menu.
